export const storefrontCatalog = [
  {
    id: 'alight-motion',
    slug: 'alight-motion',
    name: 'Alight Motion',
    category: 'Desain',
    image: 'alight-motion',
    descriptionSourceVariantId: 'am-single',
    variants: [
      {
        id: 'am-single',
        label: 'Single',
        duration: 'aktif panjang',
        providerProductId: 116,
      },
      {
        id: 'am-10',
        label: '10 Akun',
        duration: 'paketan',
        providerProductId: 117,
      },
      {
        id: 'am-25',
        label: '25 Akun',
        duration: 'paketan',
        providerProductId: 118,
      },
      {
        id: 'am-100',
        label: '100 Akun',
        duration: 'paketan',
        providerProductId: 132,
      },
    ],
  },
  {
    id: 'canva',
    slug: 'canva-pro',
    name: 'Canva Pro',
    category: 'Desain',
    image: 'canva',
    descriptionSourceVariantId: 'canva-edu',
    variants: [
      {
        id: 'canva-edu',
        label: 'EDU',
        duration: 'aktif panjang',
        providerProductId: 3,
      },
      {
        id: 'canva-invite',
        label: '1 Bulan Invite',
        duration: '1 bulan',
        providerProductId: 125,
      },
      {
        id: 'canva-head',
        label: '1 Bulan Head',
        duration: '1 bulan',
        providerProductId: 126,
      },
    ],
  },
  {
    id: 'capcut',
    slug: 'capcut-pro',
    name: 'CapCut Pro',
    category: 'Desain',
    image: 'capcut',
    descriptionSourceVariantId: 'capcut-1b',
    variants: [
      {
        id: 'capcut-1b',
        label: '1 Bulan',
        duration: '1 bulan',
        providerProductId: 1,
      },
      {
        id: 'capcut-fullgar',
        label: '1 Bulan Full Garansi',
        duration: '1 bulan',
        providerProductId: 14,
      },
    ],
  },
  {
    id: 'wink',
    slug: 'wink',
    name: 'Wink',
    category: 'Desain',
    image: 'wink',
    descriptionSourceVariantId: 'wink-1w',
    variants: [
      {
        id: 'wink-1w',
        label: '1 Minggu',
        duration: '1 minggu',
        providerProductId: 133,
      },
    ],
  },
  {
    id: 'zoom',
    slug: 'zoom',
    name: 'Zoom',
    category: 'Desain',
    image: 'zoom',
    descriptionSourceVariantId: 'zoom-1b',
    variants: [
      {
        id: 'zoom-1b',
        label: '1 Bulan',
        duration: '1 bulan',
        providerProductId: 142,
      },
    ],
  },
  {
    id: 'chatgpt-grok',
    slug: 'chatgpt-grok',
    name: 'ChatGPT & Grok',
    category: 'AI',
    image: 'ai',
    descriptionSourceVariantId: 'chatgpt-plus',
    variants: [
      {
        id: 'chatgpt-plus',
        label: 'ChatGPT Plus 1 Bulan',
        duration: '1 bulan',
        providerProductId: 12,
      },
      {
        id: 'grok-3d',
        label: 'Grok AI 3 Hari',
        duration: '3 hari',
        providerProductId: 138,
      },
    ],
  },
  {
    id: 'netflix',
    slug: 'netflix-premium',
    name: 'Netflix Premium',
    category: 'Musik & Video',
    image: 'netflix',
    descriptionSourceVariantId: 'netflix-20d',
    variants: [
      {
        id: 'netflix-20d',
        label: '20 Hari',
        duration: '20 hari',
        providerProductId: 139,
      },
    ],
  },
  {
    id: 'prime-video',
    slug: 'prime-video',
    name: 'Prime Video',
    category: 'Musik & Video',
    image: 'prime-video',
    descriptionSourceVariantId: 'prime-video',
    variants: [
      {
        id: 'prime-video',
        label: 'Akses Premium',
        duration: 'aktif',
        providerProductId: 10,
      },
    ],
  },
  {
    id: 'spotify',
    slug: 'spotify-premium',
    name: 'Spotify Premium',
    category: 'Musik & Video',
    image: 'spotify',
    descriptionSourceVariantId: 'spotify-1b',
    variants: [
      {
        id: 'spotify-1b',
        label: '1 Bulan',
        duration: '1 bulan',
        providerProductId: 5,
      },
      {
        id: 'spotify-3b',
        label: '3 Bulan',
        duration: '3 bulan',
        providerProductId: 11,
      },
    ],
  },
  {
    id: 'viu',
    slug: 'viu-premium',
    name: 'Viu Premium',
    category: 'Musik & Video',
    image: 'viu',
    descriptionSourceVariantId: 'viu-lifetime',
    variants: [
      {
        id: 'viu-lifetime',
        label: 'Lifetime',
        duration: 'lifetime',
        providerProductId: 8,
      },
      {
        id: 'viu-1tplus',
        label: '1 Tahun+',
        duration: '1 tahun+',
        providerProductId: 124,
      },
    ],
  },
  {
    id: 'youtube',
    slug: 'youtube-premium',
    name: 'YouTube Premium',
    category: 'Musik & Video',
    image: 'youtube',
    descriptionSourceVariantId: 'youtube-1b',
    variants: [
      {
        id: 'youtube-1b',
        label: '1 Bulan',
        duration: '1 bulan',
        providerProductId: 120,
      },
    ],
  },
  {
    id: 'vidio',
    slug: 'vidio-com',
    name: 'Vidio.com',
    category: 'Musik & Video',
    image: 'vidio',
    descriptionSourceVariantId: 'vidio-mobile',
    variants: [
      {
        id: 'vidio-mobile',
        label: 'Mobile 1 Bulan',
        duration: '1 bulan',
        providerProductId: 122,
      },
      {
        id: 'vidio-tv',
        label: 'TV 1 Tahun',
        duration: '1 tahun',
        providerProductId: 131,
      },
    ],
  },
  {
    id: 'streaming',
    slug: 'streaming-asia',
    name: 'Streaming',
    category: 'Musik & Video',
    image: 'streaming',
    descriptionSourceVariantId: 'wetv-1b',
    variants: [
      {
        id: 'wetv-1b',
        label: 'WeTV 1 Bulan',
        duration: '1 bulan',
        providerProductId: 128,
      },
      {
        id: 'youku-2w',
        label: 'YOUKU 2 Minggu+',
        duration: '2 minggu+',
        providerProductId: 123,
      },
      {
        id: 'shortmax-1b',
        label: 'ShortMax 1 Bulan',
        duration: '1 bulan',
        providerProductId: 140,
      },
    ],
  },
  {
    id: 'nitro',
    slug: 'discord-nitro',
    name: 'Discord Nitro',
    category: 'Musik & Video',
    image: 'nitro',
    descriptionSourceVariantId: 'nitro-3b',
    variants: [
      {
        id: 'nitro-3b',
        label: '3 Bulan',
        duration: '3 bulan',
        providerProductId: 13,
      },
    ],
  },
  {
    id: 'scribd',
    slug: 'scribd',
    name: 'Scribd',
    category: 'Musik & Video',
    image: 'scribd',
    descriptionSourceVariantId: 'scribd-1b',
    variants: [
      {
        id: 'scribd-1b',
        label: '1 Bulan',
        duration: '1 bulan',
        providerProductId: 136,
      },
    ],
  },
]
